import {
  type EnvironmentProviders,
  inject,
  provideEnvironmentInitializer,
} from '@angular/core';
import { MkIconRegistry } from './icon-registry';

/**
 * Material Symbols ligature names → built-in mk icon names. Lets templates
 * written against `<mat-icon>delete</mat-icon>` conventions keep their icon
 * names when migrating: `<mk-icon name="delete" />` renders the `trash`
 * glyph once {@link provideMkMaterialIcons} is installed.
 *
 * Several Material names intentionally collapse onto one mk glyph (all the
 * calendar variants → `calendar`, the delete variants → `trash`, …). Every
 * target is a default icon, so the aliases work without the opt-in extended
 * set. Names not listed here have no sensible built-in equivalent — register
 * your own SVG under the Material name via `MkIconRegistry.register`, or
 * alias it onto an extended glyph with `registerAliases` once
 * `provideMkExtendedIcons()` is installed (an alias whose target is missing
 * renders nothing and warns once in dev mode).
 */
export const MK_MATERIAL_ICON_ALIASES: Readonly<Record<string, string>> = {
  account_balance: 'briefcase',
  account_circle: 'user',
  add: 'plus',
  add_photo_alternate: 'image',
  add_shopping_cart: 'shopping-cart',
  admin_panel_settings: 'shield-check',
  ads_click: 'megaphone',
  analytics: 'chart-bar',
  arrow_back: 'arrow-left',
  arrow_downward: 'arrow-down',
  arrow_forward: 'arrow-right',
  arrow_upward: 'arrow-up',
  article: 'file-text',
  badge: 'tag',
  bar_chart: 'chart-bar',
  block: 'ban',
  business: 'briefcase',
  cable: 'link',
  cached: 'refresh',
  calendar_month: 'calendar',
  calendar_today: 'calendar',
  calendar_view_month: 'calendar',
  calendar_view_week: 'calendar',
  campaign: 'megaphone',
  cancel: 'error',
  card_giftcard: 'gift',
  category: 'grid',
  check: 'check',
  check_box: 'check-square',
  check_box_outline_blank: 'square',
  check_circle: 'success',
  chevron_left: 'chevron-left',
  chevron_right: 'chevron-right',
  close: 'close',
  cloud: 'cloud',
  cloud_upload: 'cloud-upload',
  code: 'code',
  content_copy: 'copy',
  credit_card: 'credit-card',
  crop: 'crop',
  dark_mode: 'moon',
  dashboard: 'dashboard',
  date_range: 'calendar',
  delete: 'trash',
  delete_forever: 'trash',
  delete_sweep: 'trash',
  description: 'file-text',
  directions_car: 'truck',
  dns: 'database',
  download: 'download',
  drag_indicator: 'grip-vertical',
  drive_file_move: 'folder',
  eco: 'leaf',
  edit: 'edit',
  egg: 'circle',
  email: 'mail',
  error: 'error',
  error_outline: 'error',
  event: 'calendar',
  event_available: 'calendar',
  event_busy: 'calendar',
  event_seat: 'users',
  expand_less: 'chevron-up',
  expand_more: 'chevron-down',
  extension: 'package',
  favorite: 'heart',
  gavel: 'briefcase',
  grain: 'leaf',
  grass: 'leaf',
  grid_view: 'grid',
  group: 'users',
  groups: 'users',
  hide_image: 'eye-off',
  history: 'history',
  home: 'home',
  hourglass_empty: 'hourglass',
  hourglass_top: 'hourglass',
  how_to_reg: 'user-check',
  image: 'image',
  info: 'info',
  inventory: 'package',
  key: 'key',
  label: 'tag',
  language: 'globe',
  light_mode: 'sun',
  link: 'link',
  link_off: 'link-off',
  list_alt: 'file-text',
  local_florist: 'leaf',
  local_offer: 'tag',
  local_shipping: 'truck',
  location_on: 'map-pin',
  lock: 'lock',
  lock_open: 'unlock',
  lock_outline: 'lock',
  lock_reset: 'key',
  login: 'log-in',
  logout: 'log-out',
  lunch_dining: 'utensils',
  mail: 'mail',
  map: 'map',
  mark_email_read: 'mail',
  mark_email_unread: 'mail',
  masks: 'shield',
  memory: 'database',
  menu: 'menu',
  menu_book: 'book-open',
  monitor_heart: 'activity',
  my_location: 'map-pin',
  notes: 'file-text',
  notifications: 'bell',
  notifications_none: 'bell',
  nutrition: 'utensils',
  open_in_new: 'external-link',
  palette: 'palette',
  pause: 'pause',
  pause_circle: 'pause',
  payment: 'credit-card',
  payments: 'banknote',
  pending: 'clock',
  people: 'users',
  person: 'user',
  person_add: 'user-plus',
  person_off: 'user-x',
  person_raised_hand: 'user',
  phone: 'phone',
  photo_library: 'image',
  place: 'map-pin',
  play_circle: 'play',
  point_of_sale: 'banknote',
  print: 'printer',
  public: 'globe',
  qr_code_scanner: 'qr-code',
  radio_button_checked: 'circle-dot',
  radio_button_unchecked: 'circle',
  receipt_long: 'file-text',
  refresh: 'refresh',
  remove: 'minus',
  remove_shopping_cart: 'shopping-cart',
  reorder: 'grip-vertical',
  replay: 'refresh',
  reply: 'undo',
  restart_alt: 'refresh',
  restaurant: 'utensils',
  restaurant_menu: 'book-open',
  reviews: 'star',
  save: 'save',
  schedule: 'clock',
  schedule_off: 'clock',
  search: 'search',
  search_off: 'search-off',
  security: 'shield',
  send: 'send',
  set_meal: 'utensils',
  settings: 'settings',
  share: 'share',
  shield: 'shield',
  shopping_bag: 'shopping-bag',
  shopping_cart: 'shopping-cart',
  spa: 'leaf',
  star: 'star',
  storage: 'database',
  storefront: 'store',
  straighten: 'sliders',
  swap_vert: 'swap-vertical',
  sync: 'refresh',
  table_restaurant: 'grid',
  table_rows: 'rows',
  task_alt: 'success',
  theater_comedy: 'users',
  today: 'calendar',
  toggle_on: 'toggle-right',
  translate: 'globe',
  trending_up: 'trending-up',
  tune: 'sliders',
  undo: 'undo',
  upload_file: 'upload',
  verified: 'shield-check',
  view_kanban: 'kanban',
  visibility: 'eye',
  visibility_off: 'eye-off',
  warning: 'warning',
  water_drop: 'droplet',
  web: 'globe',
  workspace_premium: 'award',
};

/**
 * Installs the Material Symbols name aliases into the {@link MkIconRegistry},
 * so `<mk-icon name="delete" />`, `name="expand_more"`, `name="visibility"`
 * etc. resolve to the built-in set. Add it to your bootstrap providers when
 * migrating an app off `<mat-icon>` ligatures:
 *
 * ```ts
 * bootstrapApplication(App, {
 *   providers: [provideMkMaterialIcons()],
 * });
 * ```
 */
export function provideMkMaterialIcons(): EnvironmentProviders {
  return provideEnvironmentInitializer(() =>
    inject(MkIconRegistry).registerAliases(MK_MATERIAL_ICON_ALIASES),
  );
}
