/** Delegates to `@mk-kit/core` — the exported names are unchanged. */
export {
  addDays,
  addMonths,
  buildMonthMatrix,
  clampDate,
  endOfMonth,
  endOfWeek,
  formatDate,
  formatISODate,
  getISOWeek,
  getMonthNames,
  getWeekdayFullName,
  getWeekdayNames,
  isAfter,
  isBefore,
  isSameDay,
  isSameMonth,
  parseISODate,
  startOfDay,
  startOfMonth,
  startOfWeek,
  type MkWeekday,
} from '@mk-kit/core';
