#!/usr/bin/env node
/**
 * Assemble the publishable @mk-kit/mcp package in dist/mcp:
 *   - compiled server (tsc -p projects/mcp) — run before this script
 *   - data/: the API artefacts generated by scripts/gen-api.mjs
 *   - package.json with the version of @mk-kit/ui it was built from, so
 *     `@mk-kit/mcp@X` always answers for `@mk-kit/ui@X`
 *   - README + LICENSE
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync, chmodSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const OUT = join(ROOT, 'dist/mcp');
const SRC = join(ROOT, 'projects/mcp');
const PUBLIC = join(ROOT, 'projects/docs/public');

if (!existsSync(join(OUT, 'bin.js'))) {
  console.error('dist/mcp/bin.js missing — run `tsc -p projects/mcp` first (npm run build:mcp does both).');
  process.exit(1);
}

const lib = JSON.parse(readFileSync(join(ROOT, 'projects/mk-kit/package.json'), 'utf8'));
const pkg = JSON.parse(readFileSync(join(SRC, 'package.json'), 'utf8'));
pkg.version = lib.version;
writeFileSync(join(OUT, 'package.json'), JSON.stringify(pkg, null, 2) + '\n');

mkdirSync(join(OUT, 'data'), { recursive: true });
for (const f of ['api.json', 'llms.txt', 'llms-full.txt']) copyFileSync(join(PUBLIC, f), join(OUT, 'data', f));
copyFileSync(join(SRC, 'README.md'), join(OUT, 'README.md'));
copyFileSync(join(ROOT, 'LICENSE'), join(OUT, 'LICENSE'));
chmodSync(join(OUT, 'bin.js'), 0o755);
console.log(`dist/mcp ready — @mk-kit/mcp ${pkg.version}`);
