/**
 * Generates the Lucide-derived icon files from scripts/icons.json, pulling
 * glyph bodies out of lucide-static (ISC):
 *
 *   projects/mk-kit/icon/default-icons.lucide.ts   `defaults` — glyphs the
 *       library's own components render; merged into MK_DEFAULT_ICONS so
 *       they ship with every app.
 *   projects/mk-kit/icon/extended/extended-icons.ts   `groups` — the opt-in
 *       MK_EXTENDED_ICONS map plus one MK_EXTENDED_ICONS_<GROUP> subset per
 *       group, each behind a `@__PURE__` annotation so an app only bundles
 *       the subsets it references.
 *
 * Run after editing the list: `node scripts/gen-icons.mjs`. Missing lucide
 * names are reported and skipped so a typo never silently drops the whole
 * set; a name that collides with a hand-made default is skipped too (the
 * hand-made glyph always wins).
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const spec = JSON.parse(readFileSync(join(root, 'scripts/icons.json'), 'utf8'));
const lucideDir = join(root, 'node_modules/lucide-static/icons');
const version = JSON.parse(readFileSync(join(root, 'node_modules/lucide-static/package.json'), 'utf8')).version;
const handMade = readFileSync(join(root, 'projects/mk-kit/icon/default-icons.ts'), 'utf8');

const missing = [];
const shadowed = [];
const seen = new Set();
const key = (name) => (/^[a-z]+$/.test(name) ? name : `'${name}'`);

/** `{ name: lucideFile }` → array of `  name: '<body>',` lines. */
function entriesOf(list, { skipDefaults }) {
  const out = [];
  for (const [name, file] of Object.entries(list)) {
    const path = join(lucideDir, `${file}.svg`);
    if (!existsSync(path)) { missing.push(`${name} (${file})`); continue; }
    if (seen.has(name) || (skipDefaults && new RegExp(`^\\s*'?${name.replace(/-/g, '\\-')}'?:`, 'm').test(handMade))) {
      shadowed.push(name);
      continue;
    }
    seen.add(name);
    const body = readFileSync(path, 'utf8')
      .replace(/<!--[\s\S]*?-->/g, '')
      .replace(/^[\s\S]*?<svg[^>]*>/, '')
      .replace(/<\/svg>[\s\S]*$/, '')
      .replace(/\s+/g, ' ')
      .replace(/> </g, '><')
      .trim();
    out.push(`  ${key(name)}: '${body.replace(/'/g, "\\'")}',`);
  }
  return out;
}

const header = (what) => `/**
 * GENERATED by scripts/gen-icons.mjs from scripts/icons.json — do not edit.
 *
 * ${what}
 *
 * Glyphs © Lucide Icons and Contributors, ISC licence (lucide-static
 * v${version}); see THIRD_PARTY_NOTICES.md. Bodies only — the registry-facing
 * maps wrap them with the same \`<svg>\` attributes as the hand-made defaults
 * so both sets render identically.
 */`;

// --- defaults ---------------------------------------------------------------

const defaults = entriesOf(spec.defaults ?? {}, { skipDefaults: true });
writeFileSync(
  join(root, 'projects/mk-kit/icon/default-icons.lucide.ts'),
  `${header('Lucide glyphs that the library\'s own components render (chat, query builder, …), merged into `MK_DEFAULT_ICONS` by default-icons.ts so they ship with every app.')}

/** Name → SVG body of the Lucide-derived default icons. */
export const LUCIDE_DEFAULT_ICON_BODIES: Readonly<Record<string, string>> = {
${defaults.join('\n')}
};
`,
);

// --- extended groups --------------------------------------------------------

const groups = Object.entries(spec.groups ?? {}).map(([group, list]) => ({
  group,
  constName: `MK_EXTENDED_ICONS_${group.toUpperCase().replace(/-/g, '_')}`,
  entries: entriesOf(list, { skipDefaults: true }),
}));

const groupBlocks = groups.map(
  ({ group, constName, entries }) => `/** \`${group}\` subset of {@link MK_EXTENDED_ICONS} (${entries.length} icons). */
export const ${constName}: MkIconMap = /* @__PURE__ */ S({
${entries.join('\n')}
});`,
);

const extendedDir = join(root, 'projects/mk-kit/icon/extended');
mkdirSync(extendedDir, { recursive: true });
writeFileSync(
  join(extendedDir, 'extended-icons.ts'),
  `${header('The opt-in extended icon set: `MK_EXTENDED_ICONS` (everything) and one `MK_EXTENDED_ICONS_<GROUP>` subset per themed group. Every map is built by a call marked pure, so an app pays only for the maps it actually passes to `provideMkIcons()` / `provideMkExtendedIcons()`.')}
import type { MkIconMap } from '@mk-kit/ui/icon';

/** Wraps SVG bodies with the same attributes as the hand-made defaults. */
const S = (bodies: Readonly<Record<string, string>>): MkIconMap => {
  const out: Record<string, string> = {};
  for (const name in bodies) {
    out[name] =
      \`<svg viewBox="0 0 24 24" width="100%" height="100%" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\${bodies[name]}</svg>\`;
  }
  return out;
};

${groupBlocks.join('\n\n')}

/**
 * The themed subsets by group name — handy for a picker or for registering
 * several groups at once: \`provideMkIcons(MK_EXTENDED_ICON_GROUPS['files'])\`.
 */
export const MK_EXTENDED_ICON_GROUPS: Readonly<Record<string, MkIconMap>> = {
${groups.map(({ group, constName }) => `  ${key(group)}: ${constName},`).join('\n')}
};

/**
 * Every Lucide-derived icon (${seen.size - defaults.length} glyphs). Not registered by
 * default — install it with \`provideMkExtendedIcons()\`, pass a themed subset
 * to \`provideMkIcons()\`, or load it lazily:
 * \`provideMkIcons(() => import('@mk-kit/ui/icon/extended').then((m) => m.MK_EXTENDED_ICONS))\`.
 */
export const MK_EXTENDED_ICONS: MkIconMap = /* @__PURE__ */ Object.assign(
  {},
${groups.map(({ constName }) => `  ${constName},`).join('\n')}
);
`,
);

console.log(
  `generated ${defaults.length} default + ${seen.size - defaults.length} extended icons in ${groups.length} groups (${groups.map((g) => `${g.group}:${g.entries.length}`).join(', ')})`,
);
if (shadowed.length) console.log(`skipped (already hand-made or duplicated): ${shadowed.join(', ')}`);
if (missing.length) { console.error(`MISSING in lucide-static: ${missing.join(', ')}`); process.exitCode = 1; }
