/**
 * Generates projects/mk-kit/icon/extended-icons.ts from scripts/icons.json,
 * pulling glyph bodies out of lucide-static (ISC). Run after editing the
 * list: `node scripts/gen-icons.mjs`. Missing lucide names are reported and
 * skipped so a typo never silently drops the whole set.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const list = JSON.parse(readFileSync(join(root, 'scripts/icons.json'), 'utf8')).icons;
const lucideDir = join(root, 'node_modules/lucide-static/icons');
const version = JSON.parse(readFileSync(join(root, 'node_modules/lucide-static/package.json'), 'utf8')).version;
const defaults = readFileSync(join(root, 'projects/mk-kit/icon/default-icons.ts'), 'utf8');

const entries = [];
const missing = [];
const shadowed = [];
for (const [name, file] of Object.entries(list)) {
  const path = join(lucideDir, `${file}.svg`);
  if (!existsSync(path)) { missing.push(`${name} (${file})`); continue; }
  if (new RegExp(`^\\s*'?${name.replace(/[-]/g, '\\-')}'?:`, 'm').test(defaults)) { shadowed.push(name); continue; }
  const svg = readFileSync(path, 'utf8');
  const body = svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .replace(/\s+/g, ' ')
    .replace(/> </g, '><')
    .trim();
  entries.push(`  ${/^[a-z]+$/.test(name) ? name : `'${name}'`}: S('${body.replace(/'/g, "\\'")}'),`);
}

const out = `/**
 * GENERATED by scripts/gen-icons.mjs from scripts/icons.json — do not edit.
 *
 * Glyphs © Lucide Icons and Contributors, ISC licence (lucide-static
 * v${version}); see THIRD_PARTY_NOTICES.md. Each is wrapped with the same
 * attributes as the hand-made defaults so both sets render identically.
 */
const S = (body: string): string =>
  \`<svg viewBox="0 0 24 24" width="100%" height="100%" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\${body}</svg>\`;

/** Name → SVG markup map of the Lucide-derived icons registered by default. */
export const MK_EXTENDED_ICONS: Readonly<Record<string, string>> = {
${entries.join('\n')}
};
`;
writeFileSync(join(root, 'projects/mk-kit/icon/extended-icons.ts'), out);
console.log(`generated ${entries.length} icons`);
if (shadowed.length) console.log(`skipped (already hand-made): ${shadowed.join(', ')}`);
if (missing.length) { console.error(`MISSING in lucide-static: ${missing.join(', ')}`); process.exitCode = 1; }
